config/routes.rb
Rails.application.routes.draw do
  resources :historials
  resources :servicios
  resources :animals
  resources :clientes
  devise_for :usuarios
  get 'inicio/index'
  root :to => 'inicio#index'
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=root_path%>">Veterinaria de Perritos </a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">

      <% if usuario_signed_in? %>
        <li><a href="<%= clientes_path %>">Clientes</a></li>
        <li><a href="<%= animals_path %>">Animales</a></li>
        <li><a href="<%= historials_path %>">Historial</a></li>
        <li><a href="<%= servicios_path %>">Servicios</a></li>

      <% end %>
    </ul>



      <ul class="nav navbar-nav navbar-right">
        <% if usuario_signed_in? %>
        <li><a> <%= current_usuario.email %> </a></li>
        	<li><a href="<%= edit_usuario_registration_path(current_usuario) %>">Editar Perfil</a></li>
        	<li><a href="<%= destroy_usuario_session_path %>", data-method="delete">Cerrar Session</a></li>
        <% else %>
        	<li><a href="<%= new_usuario_session_path %>">Ingresar</a></li>
        	<li><a href="<%= new_usuario_registration_path %>">Registrarse</a></li>
        <% end %>
      </ul>
    </div>
  </div><!-- /.container-fluid -->
</nav>