config/routes.rb
Rails.application.routes.draw do
  resources :historials
  resources :servicios
  resources :animals
  resources :clientes
  devise_for :usuarios
  get 'inicio/index'
  root :to => 'inicio#index'
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  belongs_to :cliente
  validates :nombre, presence: true
  validates :color, presence: true
  validates :raza, presence: true
  validates :tamano, presence: true
  validates :fechanacimiento, presence: true
  scope :recientes, ->{order("created_at desc")}

  has_many :historial
  has_many :servicio, :through => :historial
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.recientes.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
    @servicios = Servicio.all
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:nombre, :raza, :color, :tamano, :fechanacimiento, :cliente_id)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_form.html.erb
<%= form_for(@animal) do |f| %>
  <% if @animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% @animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :raza %><br>
    <%= f.text_field :raza %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :tamano %><br>
    <%= f.text_field :tamano %>
  </div>
  <div class="field">
    <%= f.label :fechanacimiento %><br>
    <%= f.date_select :fechanacimiento %>
  </div>
  <div class="field">
    <%= f.label :cliente_id %><br>
    <%= f.select("cliente_id",Cliente.all.collect{|l| [l.nombre, l.id ] }, {include_blank: 'Seleccione Cliente'}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>

<%= render 'form' %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Animals</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Raza</th>
      <th>Color</th>
      <th>Tamano</th>
      <th>Fechanacimiento</th>
      <th>Cliente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @animals.each do |animal| %>
      <tr>
        <td><%= animal.nombre %></td>
        <td><%= animal.raza %></td>
        <td><%= animal.color %></td>
        <td><%= animal.tamano %></td>
        <td><%= animal.fechanacimiento %></td>
        <td><%= animal.cliente.nombre %></td>
        <td><%= link_to 'Show', animal %></td>
        <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
        <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Animal', new_animal_path %>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render 'form' %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>

  <p>
    <strong>Nombre:</strong>
    <%= @animal.nombre %>
  </p>

  <p>
    <strong>Raza:</strong>
    <%= @animal.raza %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= @animal.color %>
  </p>

  <p>
    <strong>Tamano:</strong>
    <%= @animal.tamano %>
  </p>

  <p>
    <strong>Fecha Nacimiento:</strong>
    <%= @animal.fechanacimiento %>
  </p>

  <p>
    <strong>cliente:</strong>
    <%= @animal.cliente.nombre %>
  </p>


<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>